blueprint:
  name: Thermostat Adjustment Based on PIR Motion Sensor
  description: Adjust thermostat settings based on room occupancy detected by a PIR motion sensor.
  domain: automation
  source_url: https://github.com/the-challenge-mtas/autohome-blueprints/blob/master/temperature/PIR-thermostat.yaml
  author: AutoHome
  input:
    motion_sensor:
      name: PIR Motion Sensor
      description: The motion sensor to detect occupancy.
      selector:
        entity:
          domain: binary_sensor
          device_class: occupancy
    thermostat:
      name: Thermostat to Control
      description: The thermostat to adjust.
      selector:
        entity:
          domain: climate
    temperature_threshold:
      name: Temperature Threshold
      description: Adjust the thermostat if the temperature is below this value.
      default: 21
      selector:
        number:
          min: 10
          max: 30
          step: 0.5
          unit_of_measurement: °C

# If motion is detected within the delay,
# we restart the script.
mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input motion_sensor
    to: "on"

condition:
  - condition: numeric_state
    entity_id: !input thermostat
    attribute: current_temperature
    below: !input temperature_threshold

action:
  - service: climate.set_temperature
    target:
      entity_id: !input thermostat
    data:
      temperature: !input temperature_threshold
